### ISSUE TITLE
Using TRAP to obtain motif files

### ISSUE THREAD

**Issue by antgomo** [rajanil/msCentipede#13]
I'm a new msCentipede, and I am planning to do TF foot printing analysis using on ATACseq paired-end data.

My main concern is that I want to see if there is TF binding on my data, but first I want to look for all TFs, i.e all PWMs on JASPAR, so I am planning to use TRAP because is fast to doing this. DO you thinks is appropiate to do it?

**Comment by rajanil** [comment]
I haven't used TRAP myself. However, if the output of TRAP is a list of motif sites that a TF likely would bind to, then these sites would be an appropriate input to msCentipede. 

I've observed msCentipede to be fairly robust to the set of motif sites used for learning, as long as the set includes many potential binding sites (typically, sites with high PWM scores). So, any software (TRAP, FIMO, others ...) should suffice.

**Comment by antgomo** [comment]
OK, many thanks Anil!
