### ISSUE TITLE
FIMO scans

### ISSUE THREAD

**Issue by daquang** [rajanil/msCentipede#6]
Do you have any tips on using FIMO for scanning? I'm doing de novo motif discovery on open chromatin, and I know msCentipede requires being a good number of true binding sites, but it's hard to know whether I actually am feeding it binding sites without any ChIP data. Got any tips?

**Comment by rajanil** [comment]
In the paper describing msCentipede, we didn't use FIMO to select putative binding sites. We selected motif sites for which the ratio of likelihood of the position weight matrix for the transcription factor to the likelihood of a uniform background matrix is high (> 1000). You could use a simple peak caller on the ATAC-seq / DNase-seq data, and ensure that a reasonable fraction of motif sites in the training set fall within these peaks.
