### ISSUE TITLE
Zcat error on OSX

### ISSUE THREAD

**Issue by DoaneAS** [rajanil/msCentipede#7]
Hi,

Attempting to run the demo, and it seems there is an error related to zcat behavior on OSX.

`python call_binding.py --task learn test/CTCF_chr10_motifs.txt.gz test/Gm12878_Rep1.bam test/Gm12878_Rep2.bam`

`loading motifs ... 
zcat: can't stat: Ctcf.test.txt (Ctcf.test.txt.Z): No such file or directory`
`Traceback (most recent call last):
  File "call_binding.py", line 344, in <module>
    main()
  File "call_binding.py", line 337, in main
   learn_model(options)
  File "call_binding.py", line 32, in learn_model
    motif_handle = load_data.ZipFile(options.motif_file)
  File "/Users/asd2007/Tools/msCentipede/load_data.py", line 31, in __init__
    header = self.handle.next()
StopIteration
`

It turns out this is a known issue with differences in [zcat on OSX](https://github.com/dalibo/pgbadger/issues/70)

Possible solutions are to use `gunzip -c` in the code, or just add this [gnu-tools-for-mac.sh](https://gist.github.com/bittner/5436f3dc011d43ab7551)

Or for OSX users, install GNU coreutils, and add /usr/local/opt/coreutils/libexec/gnubin to your PATH

**Comment by EricDeveaud** [comment]
instead of using zcat, gunzip or whatever just use plain python gzip support
